/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.js';
import { Route as SecurityRouteImport } from './routes/security.js';
import { Route as OnboardingRouteImport } from './routes/onboarding.js';
import { Route as McpRouteImport } from './routes/mcp.js';
import { Route as LoginRouteImport } from './routes/login.js';
import { Route as BillingRouteImport } from './routes/billing.js';
import { Route as AppRouteImport } from './routes/app.js';
import { Route as IndexRouteImport } from './routes/index.js';
import { Route as LegalTermsRouteImport } from './routes/legal/terms.js';
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy.js';
import { Route as BillingSuccessRouteImport } from './routes/billing/success.js';
import { Route as BillingCancelRouteImport } from './routes/billing/cancel.js';

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any);
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any);
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRoute,
} as any);
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => BillingRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/app': typeof AppRoute;
  '/billing': typeof BillingRouteWithChildren;
  '/login': typeof LoginRoute;
  '/mcp': typeof McpRoute;
  '/onboarding': typeof OnboardingRoute;
  '/security': typeof SecurityRoute;
  '/billing/cancel': typeof BillingCancelRoute;
  '/billing/success': typeof BillingSuccessRoute;
  '/legal/privacy': typeof LegalPrivacyRoute;
  '/legal/terms': typeof LegalTermsRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/app': typeof AppRoute;
  '/billing': typeof BillingRouteWithChildren;
  '/login': typeof LoginRoute;
  '/mcp': typeof McpRoute;
  '/onboarding': typeof OnboardingRoute;
  '/security': typeof SecurityRoute;
  '/billing/cancel': typeof BillingCancelRoute;
  '/billing/success': typeof BillingSuccessRoute;
  '/legal/privacy': typeof LegalPrivacyRoute;
  '/legal/terms': typeof LegalTermsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/app': typeof AppRoute;
  '/billing': typeof BillingRouteWithChildren;
  '/login': typeof LoginRoute;
  '/mcp': typeof McpRoute;
  '/onboarding': typeof OnboardingRoute;
  '/security': typeof SecurityRoute;
  '/billing/cancel': typeof BillingCancelRoute;
  '/billing/success': typeof BillingSuccessRoute;
  '/legal/privacy': typeof LegalPrivacyRoute;
  '/legal/terms': typeof LegalTermsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/app'
    | '/billing'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/security'
    | '/billing/cancel'
    | '/billing/success'
    | '/legal/privacy'
    | '/legal/terms';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/app'
    | '/billing'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/security'
    | '/billing/cancel'
    | '/billing/success'
    | '/legal/privacy'
    | '/legal/terms';
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/billing'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/security'
    | '/billing/cancel'
    | '/billing/success'
    | '/legal/privacy'
    | '/legal/terms';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRoute;
  BillingRoute: typeof BillingRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  McpRoute: typeof McpRoute;
  OnboardingRoute: typeof OnboardingRoute;
  SecurityRoute: typeof SecurityRoute;
  LegalPrivacyRoute: typeof LegalPrivacyRoute;
  LegalTermsRoute: typeof LegalTermsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security';
      path: '/security';
      fullPath: '/security';
      preLoaderRoute: typeof SecurityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/mcp': {
      id: '/mcp';
      path: '/mcp';
      fullPath: '/mcp';
      preLoaderRoute: typeof McpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/billing': {
      id: '/billing';
      path: '/billing';
      fullPath: '/billing';
      preLoaderRoute: typeof BillingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/app': {
      id: '/app';
      path: '/app';
      fullPath: '/app';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/legal/terms': {
      id: '/legal/terms';
      path: '/legal/terms';
      fullPath: '/legal/terms';
      preLoaderRoute: typeof LegalTermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/legal/privacy': {
      id: '/legal/privacy';
      path: '/legal/privacy';
      fullPath: '/legal/privacy';
      preLoaderRoute: typeof LegalPrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/billing/success': {
      id: '/billing/success';
      path: '/success';
      fullPath: '/billing/success';
      preLoaderRoute: typeof BillingSuccessRouteImport;
      parentRoute: typeof BillingRoute;
    };
    '/billing/cancel': {
      id: '/billing/cancel';
      path: '/cancel';
      fullPath: '/billing/cancel';
      preLoaderRoute: typeof BillingCancelRouteImport;
      parentRoute: typeof BillingRoute;
    };
  }
}

interface BillingRouteChildren {
  BillingCancelRoute: typeof BillingCancelRoute;
  BillingSuccessRoute: typeof BillingSuccessRoute;
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
};

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BillingRoute: BillingRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  SecurityRoute: SecurityRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
