/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: web/src/theme.ts
 * Command: astryx theme build web/src/theme.ts
 * Generated: 2026-07-07T08:38:48.483Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const ziikooWoaTheme: DefinedTheme;
