/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: web/src/theme.ts
 * Command: astryx theme build web/src/theme.ts
 * Generated: 2026-07-07T08:38:48.485Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
